// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ✅ IMPORTANT: sur Chrome (Flutter Web), il faut retourner des options
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          're-run FlutterFire CLI.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKt8ihq69uA3ZCvwSw-wv79iBG1Zo6s8',
    appId: '1:423735321404:web:a4e0d361e49515a5f47439',
    messagingSenderId: '423735321404',
    projectId: 'soma-a7a5a',
    authDomain: 'soma-a7a5a.firebaseapp.com',
    storageBucket: 'soma-a7a5a.firebasestorage.app',
    measurementId: 'G-VYHPY3TK4Z',
  );

  // ✅ WEB (AJOUTÉ) : on réutilise ta config windows car ton appId est déjà "web:*"

  // ⚠️ ANDROID (PLACEHOLDER)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCms9U5f-A2mAvPCwjXUUSGjMsi4ddnWyA',
    appId: '1:423735321404:android:fe857abcbb5d3a0ff47439',
    messagingSenderId: '423735321404',
    projectId: 'soma-a7a5a',
    storageBucket: 'soma-a7a5a.firebasestorage.app',
  );

  // 👉 Pour le remplir automatiquement: relance `flutterfire configure` avec android.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5Tk24MNxk_2n9SI5nXbkzE--AEekW3A',
    appId: '1:423735321404:ios:cf672ed76645e491f47439',
    messagingSenderId: '423735321404',
    projectId: 'soma-a7a5a',
    storageBucket: 'soma-a7a5a.firebasestorage.app',
    iosBundleId: 'com.example.soma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5Tk24MNxk_2n9SI5nXbkzE--AEekW3A',
    appId: '1:423735321404:ios:cf672ed76645e491f47439',
    messagingSenderId: '423735321404',
    projectId: 'soma-a7a5a',
    storageBucket: 'soma-a7a5a.firebasestorage.app',
    iosBundleId: 'com.example.soma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKt8ihq69uA3ZCvwSw-wv79iBG1Zo6s8',
    appId: '1:423735321404:web:a4e0d361e49515a5f47439',
    messagingSenderId: '423735321404',
    projectId: 'soma-a7a5a',
    authDomain: 'soma-a7a5a.firebaseapp.com',
    storageBucket: 'soma-a7a5a.firebasestorage.app',
    measurementId: 'G-VYHPY3TK4Z',
  );

  // ✅ WINDOWS (inchangé)
}